# All algorithm in the same experiment use same confing file
# 1. Settings
exp_name: "model-heterogeneity" # name of experiment
heterogeneous: True # whether to use heterogeneous model architecture

# 2. Basic args for Federated Learning
dirichlet_alpha: 0.1
global_rounds: 30 # communication rounds
local_epochs: 1 # epochs of local update
local_loss_fn: 'CrossEntropyLoss' # loss fn name in torch.nn.*
local_optim: 'Adam'  # optimizer name in torch.optim.*, e.g. Adam, SGD
local_lr: 1e-3 # learning rate of local update
batch_size: 64 # batch_size of local update
sample_frac: 1.0 # select fraction of clients
test_interval: 1
metric_type: 'accuracy'
global_feature_dim : 256 # = generator feature dimension = classifier input dimension 

optim: 'Adam' 
optim_lr: 1e-3

# args for image generator training
global_gen_epochs : 10
gen_noise_dim: 128
gen_optim: 'Adam' # optimizer name for image-generator in torch.optim.*, e.g. Adam, SGD
gen_optim_lr: 1e-3 # learning rate of image-generator optimizer

# args for feature generator training
global_feat_gen_epochs : 10
feat_gen_noise_dim: 128
feat_gen_optim: 'Adam' # optimizer name for feature-generator in torch.optim.*, e.g. Adam, SGD
feat_gen_optim_lr: 1e-3 # learning rate of feature-generator optimizer
feat_gen_div_beta: 1.0

public_data_ratio: 0.05 # ratio of public data used for global full model update

# args for Ours
start_mapping_epoch: 1 # epoch to start learning local-to-global mapping
gen_observer_weight: 1.0 # weight for feature-generator observer loss
index_matching: 'class_name' # method for index matching, 'class_name', 'real_image', 'gan'
aggregate_method: 'dataset_name' # 'ours', 'pacfl', 'dataset_name'
use_new_entropy_method: True
entropy_ratio: 0.7

# global model
global_model_epochs: 15
global_model_optim: 'Adam' # optimizer name for global inference model in torch.optim.*, e.g. Adam, SGD
global_model_optim_lr: 1e-3 # learning rate of global inference model optimizer

global_samples_per_class: 64 # number of samples per class to train global inference model